### ISSUE TITLE
Can I make a whole new game engine based on Essential?

### ISSUE THREAD

**Issue by Davidliang11292** [Maruno17/pokemon-essentials#224]
Hello everyone, as the title suggests, I will be removing all copyrighted assets from Essentials and replacing them with assets licensed under CC BY-SA 4.0, sourced from the Tuxemon project (which is a fully free/libre and open-source monster battling RPG). Honestly, I admire the developers of Essentials for creating such a powerful game engine out of their passion. However, if my words or actions have offended anyone, please accept my sincere apologies. I believe they have taken a wrong turn resulting in their receiving a DMCA notice. It is said that Essentials carries an MIT license (please correct me if I'm mistaken), but I think it's time for Essentials to embrace true freedom and openness. If you're willing, you can join the Tuxemon Essentials project (development hasn't started yet; I'm just beginning to learn about Essentials myself, so any assistance with development would be greatly appreciated) or contribute to the original Tuxemon project. Thank you all.
![Tuxemon-Essentials-logo.jpg](https://github.com/Maruno17/pokemon-essentials/assets/152856832/05a0fdb6-879a-4d6a-90e5-be0379c62db5)

**Comment by Davidliang11292** [comment]
Supplementary note: I am merely a translator for Tuxemon, and the purpose of this project is not to replace the original Tuxemon. The reason I had the idea to create Tuxemon Essentials was because, in the past, I wanted to make my own monster-catching game. For someone like me who has only a script, it seemed that there was no better option than Essentials. However, as stated in Essentials' Wiki, due to its inclusion of copyrighted elements, using Essentials is not entirely permissible in some respects. This gave me an uneasy feeling while working with Essentials, ultimately leading me to abandon its use. I thought there might be others like me who share this predicament, and I want to help them.

**Comment by Maruno17** [comment]
I'd rather you didn't do that. The vast majority of the code in Essentials was written exclusively for Essentials, and not for another game engine, so you can't use it in yours. Tuxemon's website also claims it's written in Python, whereas Essentials is in Ruby, so I don't know how you would intend to use any of it in the first place. In any case, it would be smarter to write something better and more modern instead of reusing Essentials code.

I don't know/remember what the exact licence is that the Essentials code comes under, but it's not MIT. It boils down to "you can use it to make free games, but don't make money off it". This is incompatible with Tuxemon's CC BY-SA licence.

**Comment by FL-** [comment]
The Essentials license (at least for Essentials code) is in the root folder, as GitHub pattern: https://github.com/Maruno17/pokemon-essentials/blob/master/LICENSE

**Comment by Nathan-MV** [comment]
You can still have Essentials not use any copyrighted assets like audio and graphics and use your own assets and make a project like for example, Touhoumon using Essentials (Not a really good example as Touhoumon 1.812x Essentials use some copyrighted assets from base Essentials): https://www.pokecommunity.com/threads/touhoumon-1-812x-essentials.434622/

Note that everything on this Github does not infringe any copyright, but you wouldn't be able to make a commercial game with Essentials because of it's license.

**Comment by DerxwnaKapsyla** [comment]
Sure, you can make something unique and standalone with Essentials by purging all the copyrighted assets, but the code is still the big sticking point- it was written with Essentials, and by extention RMXP, in mind.

**Comment by Davidliang11292** [comment]
> Sure, you can make something unique and standalone with Essentials by purging all the copyrighted assets, but the code is still the big sticking point- it was written with Essentials, and by extention RMXP, in mind.

But the Essentials license is not compatible with Tuxemon's Asset License (CC BY-SA), does that mean I can't use assets from Tuxemon?

**Comment by Davidliang11292** [comment]
> Supplementary note: I am merely a translator for Tuxemon, and the purpose of this project is not to replace the original Tuxemon. The reason I had the idea to create Tuxemon Essentials was because, in the past, I wanted to make my own monster-catching game. For someone like me who has only a script, it seemed that there was no better option than Essentials. However, as stated in Essentials' Wiki, due to its inclusion of copyrighted elements, using Essentials is not entirely permissible in some respects. This gave me an uneasy feeling while working with Essentials, ultimately leading me to abandon its use. I thought there might be others like me who share this predicament, and I want to help them.

The idea is that people who are in the same predicament as me can migrate from Essentials to Tuxemon Essentials if they want to
