### ISSUE TITLE
[v21.1 Hotfixes 1.0.9] Error Message: undefined method `pbCheckEventTriggerAfterTurning' for class `Game_Event'

### ISSUE THREAD

**Issue by Carcosium** [Maruno17/pokemon-essentials#225]
When running debug mode to compile I receive this:

[Pokémon Essentials version 21.1]
[v21.1 Hotfixes 1.0.9]

Error in Plugin: [v21.1 Hotfixes]
Exception: NameError
Message: undefined method `pbCheckEventTriggerAfterTurning' for class `Game_Event'

Backtrace:
[v21.1 Hotfixes] Misc bug fixes.rb:558:in `<class:Game_Event>'
[v21.1 Hotfixes] Misc bug fixes.rb:545:in `<main>'
005_PluginManager.rb:635:in `eval'
005_PluginManager.rb:635:in `block (2 levels) in runPlugins'
005_PluginManager.rb:625:in `each'
005_PluginManager.rb:625:in `block in runPlugins'
005_PluginManager.rb:616:in `each'
005_PluginManager.rb:616:in `runPlugins'
999_Main.rb:34:in `mainFunctionDebug'
999_Main.rb:18:in `block in mainFunction'

The game compiles and runs perfectly with version 1.0.9 of Hotfixes, which I need for the Generation 9 pack. However, once I clone this repo to my project folder and replace all files as stated for installation, I get this error compiling. I've looked at all the files said to be needing replaced, but I don't see how any of them could possibly interfere, so I'm clearly overlooking or missing something. Any assistance would be greatly appreciated. I'd like to use the updates from this repo and to keep track of edits easier. Thank you!

**Comment by Maruno17** [comment]
This GitHub is not for problems with plugins.

**Comment by DeltaLeeds** [comment]
Hi @Carcosium, I fixed this issue, all you needed to do is move the alias for `pbCheckEventTriggerAfterTurning` below the method itself to use the plugin properly. Hope this helps:

So instead of

`alias __hotfixes__pbCheckEventTriggerAfterTurning pbCheckEventTriggerAfterTurning unless method_defined?(:__hotfixes__pbCheckEventTriggerAfterTurning)
  def pbCheckEventTriggerAfterTurning
    return if @map_id != $game_player.map_id
	return __hotfixes__pbCheckEventTriggerAfterTurning
  end`

the alias is moved below the method definition so that it isn't undefined.

` def pbCheckEventTriggerAfterTurning
    return if @map_id != $game_player.map_id
	return __hotfixes__pbCheckEventTriggerAfterTurning
  end
  alias __hotfixes__pbCheckEventTriggerAfterTurning pbCheckEventTriggerAfterTurning unless method_defined?(:__hotfixes__pbCheckEventTriggerAfterTurning)
`
