### ISSUE TITLE
Create a version of Pokemon Essentials for Unity or Godot

### ISSUE THREAD

**Issue by JPC16** [Maruno17/pokemon-essentials#228]
I demand that you migrate the development of Pokemon Essentials to a more modern, optimized and stable engine like Unity or Godot. Because RPG Maker XP is already a very old engine and has performance problems on modern computers.

To make you believe what I'm saying, I leave you a link to a video about a tech demo of Pokemon Unity made by IIcolour Spectrum and you can download in the link of the video description so you can try it and see how optimized it is.
https://www.youtube.com/watch?v=XozaGOtIGys&t

**Comment by Astralneko** [comment]
Quite frankly, nobody on the dev team fucking cares about this.

If you're so much of an engine elitist as to try to argue with Maruno17 about their choices, then port it to Unity your own damned self. The code is literally all right there, and it can't be that hard to convert Essentials's Ruby code to C# (the language Unity and Godot both use). In fact, if you actually looked at the project you are criticizing, you'd know that it's been packaged with mkxp-z, a plugin designed to cure RPG Maker XP's aging pains, since v19, and the version of mkxp-z packaged with the most recent version of Essentials (v21.1) was custom-built to optimize Essentials specifically. Your argument for switching engines is 3 years out of date.

Also note that Essentials started in 2010. At that time RMXP was still a relatively new engine. Minecraft has also been running on the same engine since about 2010 and complaints about how outdated Java is are negligible in that community (except to vent about spaghetti code frustrations, which any 14-year dev project will have, quite frankly). Also note that after 14 years of development, simply switching engines is going to be a difficult, if not impossible, task. But if you're so vitriolic about it, surely you have the energy to do it, right?

**Comment by DerxwnaKapsyla** [comment]
> I demand that you migrate the development of Pokemon Essentials to a more modern, optimized and stable engine like Unity or Godot. Because RPG Maker XP is already a very old engine and has performance problems on modern computers.
> 
> To make you believe what I'm saying, I leave you a link to a video about a tech demo of Pokemon Unity made by IIcolour Spectrum and you can download in the link of the video description so you can try it and see how optimized it is. https://www.youtube.com/watch?v=XozaGOtIGys&t

Make it yourself. Maruno does this for free in their spare time of their own accord, and they don't ask for anything from it aside from people to be sensible and knowledgeable about what they're doing or trying to do. This post comes off as entirely ungrateful, uncaring, and complete ignorance.
You want Essentials on a new engine? It would need to be Coded all over again from the ground up. The effort to port to a new engine would be absurd for the payoff it would give. Potentially years of reprogramming the engine. This is what you are asking for.
Perhaps before looking at what Essentials can't do and demanding what it should do, you should instead do some introspection and realize that people will not bow to demands like this, made from ignorance and malice.

**Comment by Maruno17** [comment]
This repo is for Pokémon Essentials, which is a modified RPG Maker XP game project. Any other monster-catching game engines/games, real or hypothetical, would at least belong in a different repo. Therefore this "demand" of yours is off-topic.
